Nathan h html/css company lab
PdxCodeGuild/class_olive pull request #110
Opened 2022-09-13 00:14 UTC by natekh

2022-09-13 23:37 UTC, violette-git requested changes
LOOKS really good. But when you start changing the page size you can really see what's missing. Add some responsive design and you will meet the lab requirements.

2022-09-26 22:13 UTC, natekh commented
Can you all see my latest commit on this one? I made the requested changes a while back, but not sure if it went through correctly.

2022-09-26 23:59 UTC, violette-git approved these changes
Looks good. It can only get better with practice.

2022-09-27 00:04 UTC, ChimentiMatt approved these changes

2022-09-27 00:12 UTC, closed without merging